<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0-windows10.0.18362.0</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWPF>true</UseWPF>
        <ImplicitUsings>enable</ImplicitUsings>
        <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2"/>
        <PackageReference Include="iNKORE.UI.WPF.Modern" Version="0.10.1"/>
        <PackageReference Include="Serilog" Version="4.3.1"/>
        <PackageReference Include="Syncfusion.SfGrid.WPF" Version="33.2.5"/>
    </ItemGroup>

</Project>
